[2025-07-06T20:33:43.016+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-06T20:33:43.035+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_datos_potencia.ETL.transformar_demandas_maximas manual__2025-07-06T20:33:38.394892+00:00 [queued]>
[2025-07-06T20:33:43.042+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_datos_potencia.ETL.transformar_demandas_maximas manual__2025-07-06T20:33:38.394892+00:00 [queued]>
[2025-07-06T20:33:43.043+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-06T20:33:43.054+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ETL.transformar_demandas_maximas> on 2025-07-06 20:33:38.394892+00:00
[2025-07-06T20:33:43.064+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=235) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-06T20:33:43.067+0000] {standard_task_runner.py:72} INFO - Started process 240 to run task
[2025-07-06T20:33:43.067+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag_datos_potencia', 'ETL.transformar_demandas_maximas', 'manual__2025-07-06T20:33:38.394892+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/potencia_etl_dag.py', '--cfg-path', '/tmp/tmpu3l1rcjh']
[2025-07-06T20:33:43.069+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask ETL.transformar_demandas_maximas
[2025-07-06T20:33:43.127+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_datos_potencia.ETL.transformar_demandas_maximas manual__2025-07-06T20:33:38.394892+00:00 [running]> on host b7670b46f5dc
[2025-07-06T20:33:43.223+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag_datos_potencia' AIRFLOW_CTX_TASK_ID='ETL.transformar_demandas_maximas' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T20:33:38.394892+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T20:33:38.394892+00:00'
[2025-07-06T20:33:43.225+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-06T20:33:43.250+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/potencia_etl_dag.py", line 26, in transformar_demandas_maximas
    melted_demanda_potencia = df_demanda_potencia.melt(id_vars="Meses", var_name="Año", value_name="Potencia (MW)")
                              ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'melt'
[2025-07-06T20:33:43.270+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_dag_datos_potencia, task_id=ETL.transformar_demandas_maximas, run_id=manual__2025-07-06T20:33:38.394892+00:00, execution_date=20250706T203338, start_date=20250706T203343, end_date=20250706T203343
[2025-07-06T20:33:43.295+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-06T20:33:43.296+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task ETL.transformar_demandas_maximas ('NoneType' object has no attribute 'melt'; 240)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/potencia_etl_dag.py", line 26, in transformar_demandas_maximas
    melted_demanda_potencia = df_demanda_potencia.melt(id_vars="Meses", var_name="Año", value_name="Potencia (MW)")
                              ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'melt'
[2025-07-06T20:33:43.322+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-06T20:33:43.332+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
